### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [devinsheppy/classicimmunities#1]
Version 0.0.4
WoW classic SoD

I polymorphed a wolf (ID 2959) and the tooltip says that it's polymorph immune

**Comment by devinsheppy** [comment]
Hi, thanks for submitting an issue!

Just had a quick look myself at that same mob and it isn't showing a polymorph immunity for me.

I doubled checked the database to make sure that NPC ID wasn't in by mistake and I don't see it there either.

![Screenshot 2024-04-17 163746](https://github.com/devinsheppy/classicimmunities/assets/10783495/f605f4d4-5ba1-456b-8e7a-0b92ce3540f4)

Are you able to attach a screenshot of what you see on your end?

**Comment by Alessandro-Barbieri** [comment]
![Screenshot_20240417_235738](https://github.com/devinsheppy/classicimmunities/assets/10689739/5e5c2cad-5f7b-4d86-a353-ef7ca431d7dc)

**Comment by Alessandro-Barbieri** [comment]
![Screenshot_20240418_000336](https://github.com/devinsheppy/classicimmunities/assets/10689739/113b9d80-8ffc-4784-be34-711246c62fb2)

**Comment by Alessandro-Barbieri** [comment]
There is atleast a localization issue with `UnitCreatureType` return value
see https://wowpedia.fandom.com/wiki/API_UnitCreatureType

**Comment by devinsheppy** [comment]
Yep, I see now how that would cause issues with everything. 

Thanks for the update I will look into a solution.

**Comment by Alessandro-Barbieri** [comment]
There is an useful library here https://www.wowace.com/projects/libbabble-creaturetype-3-0

**Comment by devinsheppy** [comment]
Should be fixed with the 0.0.7 version.

Thanks for helping fix this issue!

Let me know if there are any other problems.
